[package]
name = "catan-client"
version = "0.1.0"
authors = ["mrlukasbos <mrlukasbos@gmail.com>"]
edition = "2018"

[dependencies]
bufstream = "0.1"
serde_json = "1.0"
rand = "0.7.2"
serde = { version = "1.0", features = ["derive"] }
